<div class="vbout-info" style="margin-bottom: 15px;">
    <div class="vbout-logo"><img width="200" src="<?php echo $this->getSkinUrl('images/vbout/vbout-logo.png') ?>" alt="<?php echo Mage::helper('vbout')->__('Vbout') ?>"/></div>
    <div class="vbout-title"><strong><?php echo Mage::helper('vbout')->__('Vbout\'s marketing automation software saves marketers time and makes them more effective. The platform has all the tools you need to capture, nurtureand maintain clients across multiple digital marketing channels. This includes social, email, mobile and websites. Marketers using Vbout increase their efficiency, user engagement and coversion rates.'); ?></strong></div>
    <div class="vbout-link"><a title="<?php echo Mage::helper('vbout')->__('Try It Now Free'); ?>" target="_blank" href="<?php echo $this->getInfoLink(); ?>"><?php echo Mage::helper('vbout')->__('Try It Now Free'); ?></a></div>
</div>
